### ISSUE TITLE
Offload appears to confuse the quarantine thresholding logic

### ISSUE THREAD

**Issue by nwf** [CTSRD-CHERI/mrs#3]
I occasionally see things like this in the logs:
```
mrs: check_and_perform_flush (offload): passed application_quarantine threshold, offloading: allocated size 8388943 quarantine size 275162736
mrs: check_and_perform_flush (offload): passed application_quarantine threshold, offloading: allocated size 13239439 quarantine size 3319488
mrs: mrs caprevoke concurrent: efin=271 psrt=0 psro=333 psrw=154156 pfro=0 pfrw=0 pskf=120258 psks=777 cfnd=12626938 cfrv=0 cnuk=635717 lscn=4086427 pmkc=903 pcyc=1426327959 tcyc=1538162177
mrs: mrs caprevoke concurrent: efin=271 psrt=0 psro=333 psrw=38 pfro=0 pfrw=0 pskf=120258 psks=154895 cfnd=1854 cfrv=0 cnuk=35 lscn=687 pmkc=1 pcyc=582908 tcyc=63459377
mrs: mrs caprevoke final: efin=272 psrt=0 psro=333 psrw=3 pfro=0 pfrw=0 pskf=120258 psks=154930 cfnd=144 cfrv=0 cnuk=0 lscn=27 pmkc=0 pcyc=313102 tcyc=69705637
mrs: mrs caprevoke concurrent: efin=273 psrt=0 psro=333 psrw=154188 pfro=0 pfrw=0 pskf=120200 psks=803 cfnd=12218397 cfrv=2 cnuk=7440 lscn=3703961 pmkc=21 pcyc=1426082475 tcyc=1542060766
mrs: mrs caprevoke concurrent: efin=273 psrt=0 psro=333 psrw=32105 pfro=0 pfrw=0 pskf=120200 psks=122886 cfnd=2780831 cfrv=3 cnuk=0 lscn=824321 pmkc=0 pcyc=317623630 tcyc=394886172
mrs: mrs caprevoke final: efin=274 psrt=0 psro=333 psrw=19897 pfro=0 pfrw=0 pskf=120200 psks=135094 cfnd=2055813 cfrv=0 cnuk=0 lscn=542951 pmkc=0 pcyc=219223798 tcyc=296280500
```
That is, the main thread offloads a revocation, does something to its quarantine counters, and almost immediately thinks it needs to fire off another.  Meanwhile, the second core is busy executing the first revocation and then immediately executes the next (note the very low `cnuk` number on the 4th `mrs caprevoke` line relative to the first).  This double-tapping probably hurts our DRAM scores more than our cycle overhead, because offload, but all the same, it'd be nice to have it fixed.

**Comment by nwf** [comment]
Here's a full trace, or, well, up until a crash:

[471.omnetpp.mp2.cleartagsstats.mrs_revoke_offload_stats-snmalloc.txt](https://github.com/CTSRD-CHERI/mrs/files/4087145/471.omnetpp.mp2.cleartagsstats.mrs_revoke_offload_stats-snmalloc.txt)

**Comment by brettferdosi** [comment]
The quarantine threshold logic got confused because the bounds on allocations given out by snmalloc's malloc() don't match the ones given out by malloc_underlying_allocation(). Specifically, ones given by malloc() are bounded to the requested allocation size but ones given by malloc_underlying_allocation() are bounded by the underlying allocation (which is usually bigger). This means that for almost each allocation, it is accounted for by a larger number in the quarantine size than in `allocated_size`, which ultimately makes the size calculations very confused. c55ccc69364556efd5736f668ed052f481cba29d changes mrs to use the bounds given by malloc() (assuming the consumer doesn't change them) to account for the quarantine size and `allocated_size`. This seems to make things work with our current allocator setup, but ultimately I will modify the allocators to bound malloc() allocations to the underlying allocation and revert this change.

The double-tapping is intended behavior, it happens when the application thread hits the quarantine threshold while the offload thread is currently performing revocation. The confused size calculations probably caused this to happen more than it should.
